### ISSUE TITLE
Cannot run VinVL feature extraction command

### ISSUE THREAD

**Issue by lukerm** [microsoft/scene_graph_benchmark#37]
I ran the following command (from the [README](https://github.com/microsoft/scene_graph_benchmark#vinvl-feature-extraction)):

```
python tools/test_sg_net.py --config-file sgg_configs/vgattr/vinvl_x152c4.yaml TEST.IMS_PER_BATCH 2 MODEL.WEIGHT models/vinvl/vinvl_vg_x152c4.pth MODEL.ROI_HEADS.NMS_FILTER 1 MODEL.ROI_HEADS.SCORE_THRESH 0.2 DATA_DIR "../maskrcnn-benchmark-1/datasets1" TEST.IGNORE_BOX_REGRESSION True MODEL.ATTRIBUTE_ON True
```

I think the DATA_DIR is misconfigured because I get the following error (below). Where is `../maskrcnn-benchmark-1/datasets1` from? Or the file [`visualgenome/test_vgoi6_clipped.yaml`](https://github.com/microsoft/scene_graph_benchmark/blob/main/sgg_configs/vgattr/vinvl_x152c4.yaml#L35), which I think it's looking for?

This is the AssertionError:
```
Traceback (most recent call last):
  File "tools/test_sg_net.py", line 197, in <module>
    main()
  File "tools/test_sg_net.py", line 193, in main
    run_test(cfg, model, args.distributed, model_name)
  File "tools/test_sg_net.py", line 55, in run_test
    data_loaders_val = make_data_loader(cfg, is_train=False, is_distributed=distributed)
  File "/scene_graph_benchmark/maskrcnn_benchmark/data/build.py", line 170, in make_data_loader
    datasets = build_dataset(cfg, transforms, DatasetCatalog, is_train or is_for_period)
  File "/scene_graph_benchmark/maskrcnn_benchmark/data/build.py", line 45, in build_dataset
    cfg, dataset_name, factory_name, is_train
  File "/scene_graph_benchmark/maskrcnn_benchmark/data/datasets/utils/config_args.py", line 7, in config_tsv_dataset_args
    assert op.isfile(full_yaml_file)
AssertionError
```

Thanks in advance!

**Comment by joeyy5588** [comment]
You can download the dataset following the instruction in the **Perform training** section in readme.
The path to your yaml file would be DATA_DIR followed by DATASETS.TEST in your testing config ("../maskrcnn-benchmark-1/datasets1" + "visualgenome/test_vgoi6_clipped.yaml") for example.

**Comment by lukerm** [comment]
I have downloaded the data, but have not found `test_vgoi6_clipped.yaml`. Here are the steps I took:

```
$ ./azcopy copy 'https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/datasets/visualgenome' data --recursive
INFO: Scanning...
INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job 1b034082-73a8-0a41-67de-1ae538b27c87 has started
```

The downloaded YAML files does not include `test_vgoi6_clipped.yaml`

```
$ ls -la data/visualgenome/*.yaml 
-rw-r--r-- 1 ubuntu ubuntu 169 Aug  2 13:06 data/visualgenome/test_danfeiX_relation.yaml
-rw-r--r-- 1 ubuntu ubuntu 170 Aug  2 13:06 data/visualgenome/train_danfeiX_relation_nm.yaml
```
For your reference, here is everything that was downloaded:

```
$ ls -la data/visualgenome/                        
total 20264496
drwxrwxr-x 2 ubuntu ubuntu        4096 Aug  2 13:11 .
drwxrwxr-x 3 ubuntu ubuntu        4096 Aug  2 13:06 ..
-rw-r--r-- 1 ubuntu ubuntu      835049 Aug  2 13:06 hw.lineidx
-rw-r--r-- 1 ubuntu ubuntu     4108316 Aug  2 13:06 hw.tsv
-rw-r--r-- 1 ubuntu ubuntu     1241364 Aug  2 13:06 img.lineidx
-rw-r--r-- 1 ubuntu ubuntu 20439590250 Aug  2 13:11 img.tsv
-rw-r--r-- 1 ubuntu ubuntu     4651532 Aug  2 13:06 label_danfeiX_clipped.freq_prior.npy
-rw-r--r-- 1 ubuntu ubuntu     4651532 Aug  2 13:06 label_danfeiX_clipped.new.freq_prior.npy
-rw-r--r-- 1 ubuntu ubuntu      997885 Aug  2 13:06 label_danfeiX_clipped.new.lineidx
-rw-r--r-- 1 ubuntu ubuntu   145570762 Aug  2 13:06 label_danfeiX_clipped.new.tsv
-rw-r--r-- 1 ubuntu ubuntu      165464 Aug  2 13:06 label_danfeiX_clipped.relation.test.linelist.tsv
-rw-r--r-- 1 ubuntu ubuntu     4651532 Aug  2 13:06 label_danfeiX_overlap.new.freq_prior.npy
-rw-r--r-- 1 ubuntu ubuntu      996497 Aug  2 13:06 label_danfeiX_overlap.new.lineidx
-rw-r--r-- 1 ubuntu ubuntu   142911783 Aug  2 13:07 label_danfeiX_overlap.new.tsv
-rw-r--r-- 1 ubuntu ubuntu      356521 Aug  2 13:06 label_danfeiX_overlap.relation.train.linelist.tsv
-rw-r--r-- 1 ubuntu ubuntu         169 Aug  2 13:06 test_danfeiX_relation.yaml
-rw-r--r-- 1 ubuntu ubuntu         170 Aug  2 13:06 train_danfeiX_relation_nm.yaml
-rw-r--r-- 1 ubuntu ubuntu       28453 Aug  2 13:06 VG-SGG-dicts-danfeiX-clipped.json
-rw-r--r-- 1 ubuntu ubuntu       28453 Aug  2 13:06 VG-SGG-dicts-danfeiX-overlap.json
```

Is there somewhere else I should download it from?

**Comment by linxi1158** [comment]
I have the same problem

**Comment by linxi1158** [comment]
> You can download the dataset following the instruction in the **Perform training** section in readme.
> The path to your yaml file would be DATA_DIR followed by DATASETS.TEST in your testing config ("../maskrcnn-benchmark-1/datasets1" + "visualgenome/test_vgoi6_clipped.yaml") for example.



> I have downloaded the data, but have not found `test_vgoi6_clipped.yaml`. Here are the steps I took:
> 
> ```
> $ ./azcopy copy 'https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/datasets/visualgenome' data --recursive
> INFO: Scanning...
> INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
> 
> Job 1b034082-73a8-0a41-67de-1ae538b27c87 has started
> ```
> 
> The downloaded YAML files does not include `test_vgoi6_clipped.yaml`
> 
> ```
> $ ls -la data/visualgenome/*.yaml 
> -rw-r--r-- 1 ubuntu ubuntu 169 Aug  2 13:06 data/visualgenome/test_danfeiX_relation.yaml
> -rw-r--r-- 1 ubuntu ubuntu 170 Aug  2 13:06 data/visualgenome/train_danfeiX_relation_nm.yaml
> ```
> 
> For your reference, here is everything that was downloaded:
> 
> ```
> $ ls -la data/visualgenome/                        
> total 20264496
> drwxrwxr-x 2 ubuntu ubuntu        4096 Aug  2 13:11 .
> drwxrwxr-x 3 ubuntu ubuntu        4096 Aug  2 13:06 ..
> -rw-r--r-- 1 ubuntu ubuntu      835049 Aug  2 13:06 hw.lineidx
> -rw-r--r-- 1 ubuntu ubuntu     4108316 Aug  2 13:06 hw.tsv
> -rw-r--r-- 1 ubuntu ubuntu     1241364 Aug  2 13:06 img.lineidx
> -rw-r--r-- 1 ubuntu ubuntu 20439590250 Aug  2 13:11 img.tsv
> -rw-r--r-- 1 ubuntu ubuntu     4651532 Aug  2 13:06 label_danfeiX_clipped.freq_prior.npy
> -rw-r--r-- 1 ubuntu ubuntu     4651532 Aug  2 13:06 label_danfeiX_clipped.new.freq_prior.npy
> -rw-r--r-- 1 ubuntu ubuntu      997885 Aug  2 13:06 label_danfeiX_clipped.new.lineidx
> -rw-r--r-- 1 ubuntu ubuntu   145570762 Aug  2 13:06 label_danfeiX_clipped.new.tsv
> -rw-r--r-- 1 ubuntu ubuntu      165464 Aug  2 13:06 label_danfeiX_clipped.relation.test.linelist.tsv
> -rw-r--r-- 1 ubuntu ubuntu     4651532 Aug  2 13:06 label_danfeiX_overlap.new.freq_prior.npy
> -rw-r--r-- 1 ubuntu ubuntu      996497 Aug  2 13:06 label_danfeiX_overlap.new.lineidx
> -rw-r--r-- 1 ubuntu ubuntu   142911783 Aug  2 13:07 label_danfeiX_overlap.new.tsv
> -rw-r--r-- 1 ubuntu ubuntu      356521 Aug  2 13:06 label_danfeiX_overlap.relation.train.linelist.tsv
> -rw-r--r-- 1 ubuntu ubuntu         169 Aug  2 13:06 test_danfeiX_relation.yaml
> -rw-r--r-- 1 ubuntu ubuntu         170 Aug  2 13:06 train_danfeiX_relation_nm.yaml
> -rw-r--r-- 1 ubuntu ubuntu       28453 Aug  2 13:06 VG-SGG-dicts-danfeiX-clipped.json
> -rw-r--r-- 1 ubuntu ubuntu       28453 Aug  2 13:06 VG-SGG-dicts-danfeiX-overlap.json
> ```
> 
> Is there somewhere else I should download it from?

I have the same problem

**Comment by hikaru-nara** [comment]
Same problem here

**Comment by cwkeam** [comment]
Same problem here

**Comment by cwkeam** [comment]
We'll definitely need the proper inputs from the actual developers of this package, but seeing that this test_vgoi_clipped.yaml file probably serves the same function, one way to see the code run is by just doing

`mv test_danfeiX_relation.yaml test_vgoi_clipped.yaml
`
thought it made some sense considering that the purpose of this yaml file is just to point the code to the dataset files, and seems like all the dataset files in this visual genome are these "*_danfeiX_*" files.

**Comment by linxi1158** [comment]
> We'll definitely need the proper inputs from the actual developers of this package, but seeing that this test_vgoi_clipped.yaml file probably serves the same function, one way to see the code run is by just doing
> 
> `mv test_danfeiX_relation.yaml test_vgoi_clipped.yaml `
> thought it made some sense considering that the purpose of this yaml file is just to point the code to the dataset files, and seems like all the dataset files in this visual genome are these "__danfeiX__" files.

ok, thanks

**Comment by via815via** [comment]
> > We'll definitely need the proper inputs from the actual developers of this package, but seeing that this test_vgoi_clipped.yaml file probably serves the same function, one way to see the code run is by just doing
> > `mv test_danfeiX_relation.yaml test_vgoi_clipped.yaml `
> > thought it made some sense considering that the purpose of this yaml file is just to point the code to the dataset files, and seems like all the dataset files in this visual genome are these "**danfeiX**" files.
> 
> ok, thanks

Do you solve this problem? Can you tell me? Thanks very much!

**Comment by Lxy811** [comment]
> I have downloaded the data, but have not found `test_vgoi6_clipped.yaml`. Here are the steps I took:
> 
> ```
> $ ./azcopy copy 'https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/datasets/visualgenome' data --recursive
> INFO: Scanning...
> INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support
> 
> Job 1b034082-73a8-0a41-67de-1ae538b27c87 has started
> ```
> 
> The downloaded YAML files does not include `test_vgoi6_clipped.yaml`
> 
> ```
> $ ls -la data/visualgenome/*.yaml 
> -rw-r--r-- 1 ubuntu ubuntu 169 Aug  2 13:06 data/visualgenome/test_danfeiX_relation.yaml
> -rw-r--r-- 1 ubuntu ubuntu 170 Aug  2 13:06 data/visualgenome/train_danfeiX_relation_nm.yaml
> ```
> 
> For your reference, here is everything that was downloaded:
> 
> ```
> $ ls -la data/visualgenome/                        
> total 20264496
> drwxrwxr-x 2 ubuntu ubuntu        4096 Aug  2 13:11 .
> drwxrwxr-x 3 ubuntu ubuntu        4096 Aug  2 13:06 ..
> -rw-r--r-- 1 ubuntu ubuntu      835049 Aug  2 13:06 hw.lineidx
> -rw-r--r-- 1 ubuntu ubuntu     4108316 Aug  2 13:06 hw.tsv
> -rw-r--r-- 1 ubuntu ubuntu     1241364 Aug  2 13:06 img.lineidx
> -rw-r--r-- 1 ubuntu ubuntu 20439590250 Aug  2 13:11 img.tsv
> -rw-r--r-- 1 ubuntu ubuntu     4651532 Aug  2 13:06 label_danfeiX_clipped.freq_prior.npy
> -rw-r--r-- 1 ubuntu ubuntu     4651532 Aug  2 13:06 label_danfeiX_clipped.new.freq_prior.npy
> -rw-r--r-- 1 ubuntu ubuntu      997885 Aug  2 13:06 label_danfeiX_clipped.new.lineidx
> -rw-r--r-- 1 ubuntu ubuntu   145570762 Aug  2 13:06 label_danfeiX_clipped.new.tsv
> -rw-r--r-- 1 ubuntu ubuntu      165464 Aug  2 13:06 label_danfeiX_clipped.relation.test.linelist.tsv
> -rw-r--r-- 1 ubuntu ubuntu     4651532 Aug  2 13:06 label_danfeiX_overlap.new.freq_prior.npy
> -rw-r--r-- 1 ubuntu ubuntu      996497 Aug  2 13:06 label_danfeiX_overlap.new.lineidx
> -rw-r--r-- 1 ubuntu ubuntu   142911783 Aug  2 13:07 label_danfeiX_overlap.new.tsv
> -rw-r--r-- 1 ubuntu ubuntu      356521 Aug  2 13:06 label_danfeiX_overlap.relation.train.linelist.tsv
> -rw-r--r-- 1 ubuntu ubuntu         169 Aug  2 13:06 test_danfeiX_relation.yaml
> -rw-r--r-- 1 ubuntu ubuntu         170 Aug  2 13:06 train_danfeiX_relation_nm.yaml
> -rw-r--r-- 1 ubuntu ubuntu       28453 Aug  2 13:06 VG-SGG-dicts-danfeiX-clipped.json
> -rw-r--r-- 1 ubuntu ubuntu       28453 Aug  2 13:06 VG-SGG-dicts-danfeiX-overlap.json
> ```
> 
> Is there somewhere else I should download it from?

Can you share the downloaded data?
