### ISSUE TITLE
Docker image broken

### ISSUE THREAD

**Issue by dreamflasher** [microsoft/scene_graph_benchmark#69]
This Dockerfile https://github.com/microsoft/scene_graph_benchmark/blob/main/docker/Dockerfile has the relevant lines of installing the repo commented out.

Uncommenting them and building the images results in:

```
/miniconda/envs/py37/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370141920/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/miniconda/envs/py37/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/miniconda/envs/py37/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/miniconda/envs/py37/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/miniconda/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/miniconda/envs/py37/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/miniconda/envs/py37/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/miniconda/envs/py37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/miniconda/envs/py37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/miniconda/envs/py37/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/miniconda/envs/py37/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/miniconda/envs/py37/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/miniconda/envs/py37/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 486, in unix_wrap_ninja_compile
    cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 395, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags) +
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1424, in _get_cuda_arch_flags
    capability = torch.cuda.get_device_capability()
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/cuda/__init__.py", line 291, in get_device_capability
    prop = get_device_properties(device)
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/cuda/__init__.py", line 296, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/miniconda/envs/py37/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by dreamflasher** [comment]
This command can be used to install the library after building the image: `sudo docker run --rm --gpus all -it --entrypoint bash scene_graph_benchmark`

**Comment by dreamflasher** [comment]
But then running the code fails with:

```
root@1758423ba0b9:/scene_graph_benchmark# python tools/demo/demo_image.py --config_file sgg_configs/vgattr/vinvl_x152c4.yaml --img_file demo/woman_fish.jpg --save_file output/woman_fish_x152c4.obj.jpg MODEL.WEIGHT pretrained_model/vinvl_vg_x152c4.pth MODEL.ROI_HEADS.NMS_FILTER 1 MODEL.ROI_HEADS.SCORE_THRESH 0.2 TEST.IGNORE_BOX_REGRESSION False
Traceback (most recent call last):
  File "tools/demo/demo_image.py", line 3, in <module>
    import cv2
  File "/miniconda/envs/py37/lib/python3.7/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by dreamflasher** [comment]
The Dockerfile needs: `RUN apt-get install ffmpeg libsm6 libxext6  -y`

**Comment by albertmundu** [comment]
> But then running the code fails with:
> 
> ```
> root@1758423ba0b9:/scene_graph_benchmark# python tools/demo/demo_image.py --config_file sgg_configs/vgattr/vinvl_x152c4.yaml --img_file demo/woman_fish.jpg --save_file output/woman_fish_x152c4.obj.jpg MODEL.WEIGHT pretrained_model/vinvl_vg_x152c4.pth MODEL.ROI_HEADS.NMS_FILTER 1 MODEL.ROI_HEADS.SCORE_THRESH 0.2 TEST.IGNORE_BOX_REGRESSION False
> Traceback (most recent call last):
>   File "tools/demo/demo_image.py", line 3, in <module>
>     import cv2
>   File "/miniconda/envs/py37/lib/python3.7/site-packages/cv2/__init__.py", line 8, in <module>
>     from .cv2 import *
> ImportError: libGL.so.1: cannot open shared object file: No such file or directory
> ```

Need to install `libgl-dev` package

**Comment by dreamflasher** [comment]
Yeah it needs ˋˋˋ
 apt-get install ffmpeg libsm6 libxext6  -y
 
 git clone https://github.com/microsoft/scene_graph_benchmark.git  && cd scene_graph_benchmark  && python setup.py build develop
 
 pip install  torchvision==0.8.2+cu101 --find-links=https://download.pytorch.org/whl/torch_stable.html
 
 mkdir pretrained_model && cd pretrained_model
 wget https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/vinvl_vg_x152c4.pth
 cd ..
 
 mkdir visualgenome && cd visualgenome
 wget https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/VG-SGG-dicts-vgoi6-clipped.json
 cd ..
ˋˋˋ

I'm working on a PR, but so far I wasn't able to build the library from the Docker build command, because it's missing the gpu then.

**Comment by SamratThapa120** [comment]
If anyone still has this issue. I was able to build the image with the following:

```
# ARG CUDA="10.1"
# ARG CUDNN="7"

   
FROM nvcr.io/nvidia/pytorch:21.03-py3

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# install basics
RUN apt-get update -y \
 && apt-get install -y libgl1-mesa-dev \
 && apt-get install -y apt-utils git curl ca-certificates bzip2 cmake tree htop bmon iotop g++ \
 && apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev libyaml-dev vim zsh wget htop tmux

# Install Miniconda
RUN curl -so /miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
 && chmod +x /miniconda.sh \
 && /miniconda.sh -b -p /miniconda \
 && rm /miniconda.sh

ENV PATH=/miniconda/bin:$PATH

# Create a Python 3.7 environment
RUN /miniconda/bin/conda install -y conda-build \
 && /miniconda/bin/conda create -y --name py37 python=3.7 \
 && /miniconda/bin/conda clean -ya

ENV CONDA_DEFAULT_ENV=py37
ENV CONDA_PREFIX=/miniconda/envs/$CONDA_DEFAULT_ENV
ENV PATH=$CONDA_PREFIX/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false

RUN conda install -y ipython h5py nltk joblib jupyter pandas scipy
RUN pip install requests ninja cython yacs>=0.1.8 numpy>=1.19.5 cython matplotlib opencv-python tqdm \
 protobuf tensorboardx pymongo sklearn boto3 scikit-image cityscapesscripts
RUN pip install azureml-defaults>=1.0.45 azureml.core inference-schema
RUN pip --no-cache-dir install --force-reinstall -I pyyaml

RUN python -m nltk.downloader punkt

# Install latest PyTorch 1.7.1
# ARG CUDA
RUN conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.1 -c pytorch \
 && conda clean -ya
RUN conda install -y -c conda-forge timm einops

# install pycocotools
# RUN git clone https://github.com/cocodataset/cocoapi.git \
#  && cd cocoapi/PythonAPI \
#  && python setup.py build_ext install
RUN conda install -y -c conda-forge pycocotools

# install cityscapesScripts
RUN python -m pip install cityscapesscripts

# install PyTorch Detection
ARG FORCE_CUDA="1"
ENV FORCE_CUDA=${FORCE_CUDA}

RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true
RUN echo """export ZSH="/root/.oh-my-zsh"\nZSH_THEME="gentoo"\nplugins=(git)\nsource \$ZSH/oh-my-zsh.sh""" > /root/.zshrc
RUN echo """syntax on\nfiletype indent on\nset autoindent\nset number\ncolorscheme desert""" > /root/.vimrc

CMD [ "zsh" ]

RUN git clone https://github.com/microsoft/scene_graph_benchmark.git \
 && cd scene_graph_benchmark \
 && python setup.py build develop

WORKDIR /scene_graph_benchmark
```

**Comment by iamzifei** [comment]
> Yeah it needs ˋˋˋ apt-get install ffmpeg libsm6 libxext6 -y
> 
> git clone https://github.com/microsoft/scene_graph_benchmark.git && cd scene_graph_benchmark && python setup.py build develop
> 
> pip install torchvision==0.8.2+cu101 --find-links=https://download.pytorch.org/whl/torch_stable.html
> 
> mkdir pretrained_model && cd pretrained_model wget https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/vinvl_vg_x152c4.pth cd ..
> 
> mkdir visualgenome && cd visualgenome wget https://penzhanwu2.blob.core.windows.net/sgg/sgg_benchmark/vinvl_model_zoo/VG-SGG-dicts-vgoi6-clipped.json cd .. ˋˋˋ
> 
> I'm working on a PR, but so far I wasn't able to build the library from the Docker build command, because it's missing the gpu then.

I'm able to build the docker image without commenting out the bottom of the docker file, but I cannot clone the repo and build it manually inside the docker container afterwards. It has " Error compiling objects for extension"

If I include the git clone and build in the docker file, then I get no CUDA driver error when building the image.

I'm wondering have you solved the issue and successfully run the docker instance? If so, could you share some details please?

**Comment by SamratThapa120** [comment]
Here is my dockerfile. It runs without errors for me.
```
ARG CUDA="11.1"
ARG CUDNN="7"

   
FROM nvcr.io/nvidia/pytorch:20.10-py3
RUN python -c "import torch,torchvision; print(torch.__version__,torchvision.__version__)"

ARG CUDA

# RUN pip uninstall pytorch torchvision cuda80 -c soumith
# RUN pip uninstall -y torch torchvision torchaudio cudatoolkit

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# install basics
RUN apt-get update -y \
 && apt-get install -y libgl1-mesa-dev \
 && apt-get install -y apt-utils git curl ca-certificates bzip2 cmake tree htop bmon iotop g++ \
 && apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev libyaml-dev vim zsh wget htop tmux

# Install Miniconda
RUN curl -so /miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
 && chmod +x /miniconda.sh \
 && /miniconda.sh -b -p /miniconda \
 && rm /miniconda.sh

ENV PATH=/miniconda/bin:$PATH

# Create a Python 3.7 environment
RUN /miniconda/bin/conda install -y conda-build \
 && /miniconda/bin/conda create -y --name py37 python=3.7 \
 && /miniconda/bin/conda clean -ya

ENV CONDA_DEFAULT_ENV=py37
ENV CONDA_PREFIX=/miniconda/envs/$CONDA_DEFAULT_ENV
ENV PATH=$CONDA_PREFIX/bin:$PATH
ENV CONDA_AUTO_UPDATE_CONDA=false

RUN conda install -y ipython h5py nltk joblib jupyter pandas scipy
RUN pip install requests ninja cython yacs>=0.1.8 numpy>=1.19.5 cython matplotlib opencv-python tqdm \
 protobuf tensorboardx pymongo sklearn boto3 scikit-image cityscapesscripts
RUN pip install azureml-defaults>=1.0.45 azureml.core inference-schema
RUN pip --no-cache-dir install --force-reinstall -I pyyaml

RUN python -m nltk.downloader punkt

# Install latest PyTorch 1.7.1
ARG CUDA
RUN conda install pytorch==1.7.1 torchvision torchaudio -c pytorch \
 && conda clean -ya
RUN conda install -y -c conda-forge timm einops

# install pycocotools
# RUN git clone https://github.com/cocodataset/cocoapi.git \
#  && cd cocoapi/PythonAPI \
#  && python setup.py build_ext install
RUN conda install -y -c conda-forge pycocotools

# install cityscapesScripts
RUN python -m pip install cityscapesscripts

# install PyTorch Detection
ARG FORCE_CUDA="1"
ENV FORCE_CUDA=${FORCE_CUDA}

RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true
RUN echo """export ZSH="/root/.oh-my-zsh"\nZSH_THEME="gentoo"\nplugins=(git)\nsource \$ZSH/oh-my-zsh.sh""" > /root/.zshrc
RUN echo """syntax on\nfiletype indent on\nset autoindent\nset number\ncolorscheme desert""" > /root/.vimrc

CMD [ "zsh" ]

RUN git clone https://github.com/microsoft/scene_graph_benchmark.git \
 && cd scene_graph_benchmark \
 && python setup.py build develop

WORKDIR /scene_graph_benchmark
```
